version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playground
    volumes:
      - ./__tests__:/app/__tests__
      - ../testcase:/app/testcase
      - ./basic_grammar:/app/basic_grammar
      - ./stl:/app/stl
      - ./algorithm:/app/algorithm
      - ./code_recipe:/app/code_recipe
      - ./package.json:/app/package.json
    command: yarn execute
    # command: yarn test:ci
    # command: yarn test:coverage